version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "01:00"
    timezone: Europe/Berlin
  target-branch: "development"
  open-pull-requests-limit: 2
  labels:
  - dependencies
  versioning-strategy: increase